# Terminal settings
# set -g default-terminal "tmux-256color"
# set -ag terminal-overrides "xterm-256color:RGB"
# set -g default-terminal "screen-256color"

set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# Unbind default Ctrl + b
unbind C-b
set-option -g prefix C-a
set-option -g repeat-time 0

#key bindings
bind-key -n C-v split-window -h
bind-key -n C-x split-window -v

bind-key -n C-t new-window
bind -r w previous-window
bind -r e next-window

bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

#Essentials
set-option -g default-shell /bin/zsh

set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M
bind -n C-WheelUpPane select-pane -t= \; copy-mode -e \; send-keys -M
setw -g mode-keys vi
set -g status off

#Status customization
# set -g status-bg '#3b4252'
# set -g status-fg '#93A1A1'
# set -g pane-border-style fg='#525a6c'
# set -g pane-active-border-style "bg=#525a6c fg=#525a6c"
# set -g status-position bottom

# set -g pane-border-style fg="#3b4252"
# set -g pane-active-border-style fg="#184E4A"
# set -g window-status-current-style bg="#6ac0ff",fg="#242424"
# set-window-option -g window-status-current-format "#[fg=#3b4252, bg=#6ac0ff] #[fg=black, bg=#6ac0ff] #W #[fg=#6ac0ff, bg=#3b4252]" 
# set-window-option -g window-status-format "#[fg=#3b4252, bg=#525a6c] #[fg=#93A1A1, bg=#525a6c] #W #[fg=#525a6c, bg=#3b4252]"

# set-window-option -g window-status-current-format "#[fg=black, bg=#6ac0ff] #W #[fg=#6ac0ff, bg=#3b4252]" 
# set-window-option -g window-status-format "#[fg=#93A1A1, bg=#525a6c] #W #[fg=#525a6c, bg=#3b4252]"

# I use Arch BTW
set -g status-left " 󰄛 "

#Pluggins > Ctrl+a then Shift+i
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'frappe' # or frappe, macchiato, mocha

set -g @catppuccin_powerline_icons_theme_enabled on
set -g @catppuccin_window_tabs_enabled on
set -g @catppuccin_l_left_separator ""
set -g @catppuccin_l_right_separator ""
set -g @catppuccin_r_left_separator ""
set -g @catppuccin_r_right_separator ""

run '~/.tmux/plugins/tpm/tpm'
