palette = "catppuccin_frappe"

format = """
[┌─\\(](fg:green)\
[typ0 ㉿legion](fg:blue)\
[\\)─](fg:green)\
[\\[](fg:green)\
$directory\
[\\]](fg:green)\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$python\
$php\
\n[└─](fg:green)\
$character"""

# format = """
# [](fg:surface2)\
# [ typ0 ](bg:surface2 fg:blue)\
# [](fg:surface2 bg:blue)\
# $directory\
# [](fg:blue bg:green)\
# $git_branch\
# $git_status\
# [ ](green)\
# $nodejs\
# $rust\
# $golang\
# $python\
# $php\
# \n$character"""

add_newline = true

[character]
success_symbol = "[\\$](blue)"
error_symbol = "[\\$](red)"
vimcmd_symbol = "[❮](green)"

[directory]
style = "fg:white"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "~/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:green"
format = '[[ $symbol $branch ](fg:green)]($style)'

[git_status]
# style = "bg:green"
format = '[[($all_status$ahead_behind )](fg:green)]($style)'

[nodejs]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:blue)]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:blue)]($style)'

[golang]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:blue)]($style)'

[python]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:blue)]($style)'

[php]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:blue)]($style)'

[gcloud]
format = '[$symbol$active]($style) '
style = 'bold yellow'

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
